import { useState, useEffect, useCallback } from "react";
import { motion } from "framer-motion";
import { api } from "../api";
import Markdown from "./Markdown";

const KINDS = [
  ["outline", "Outline"],
  ["email", "Email"],
  ["checklist", "Checklist"],
  ["steps", "Steps"],
];

/** AI "Kickstart" modal — drafts a head-start artifact for a task.
 *  Shared by Today and Reality Check. Closes via ✕ or backdrop click. */
export default function KickstartModal({ task, onClose, initialKind = null }) {
  const [kind, setKind] = useState(initialKind);
  const [draft, setDraft] = useState("");
  const [loading, setLoading] = useState(true);
  const [usedAi, setUsedAi] = useState(false);
  const [copied, setCopied] = useState(false);

  const load = useCallback(
    async (k, fresh = false) => {
      setLoading(true);
      try {
        const res = await api.kickstart(task.id, k, fresh);
        setDraft(res.draft);
        setKind(res.kind);
        setUsedAi(res.ai);
      } catch {
        setDraft("Couldn't generate a draft right now. Please try again.");
      } finally {
        setLoading(false);
      }
    },
    [task.id]
  );

  useEffect(() => {
    load(initialKind);
  }, [load, initialKind]);

  // Close on Escape.
  useEffect(() => {
    const onKey = (e) => e.key === "Escape" && onClose();
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [onClose]);

  function copy() {
    navigator.clipboard?.writeText(draft);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      onClick={onClose}
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm"
    >
      <motion.div
        initial={{ opacity: 0, scale: 0.94, y: 12 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.96, y: 8 }}
        transition={{ type: "spring", stiffness: 320, damping: 28 }}
        onClick={(e) => e.stopPropagation()}
        className="bg-surface-container border border-outline-variant/40 rounded-2xl p-unit-lg w-full max-w-2xl shadow-2xl max-h-[85vh] flex flex-col"
      >
        <div className="flex items-start justify-between mb-unit-md">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-primary/15 flex items-center justify-center shrink-0">
              <span className="material-symbols-outlined text-primary">bolt</span>
            </div>
            <div>
              <h3 className="font-headline-md text-headline-md font-bold text-on-surface leading-tight">
                Kickstart
              </h3>
              <p className="text-label-md text-on-surface-variant">{task.title}</p>
            </div>
          </div>
          <button onClick={onClose} className="text-on-surface-variant hover:text-on-surface">
            <span className="material-symbols-outlined">close</span>
          </button>
        </div>

        <div className="flex gap-2 mb-unit-md flex-wrap">
          {KINDS.map(([k, label]) => (
            <button
              key={k}
              onClick={() => load(k)}
              className={`px-3 py-1.5 rounded-lg text-label-md font-bold transition-colors ${
                kind === k
                  ? "bg-primary text-on-primary-fixed"
                  : "bg-surface-container-high text-on-surface-variant hover:bg-surface-container-highest"
              }`}
            >
              {label}
            </button>
          ))}
        </div>

        <div className="flex-1 overflow-y-auto bg-surface-container-lowest border border-outline-variant/30 rounded-xl p-unit-md min-h-[160px]">
          {loading ? (
            <div className="flex items-center justify-center h-40 gap-2 text-on-surface-variant">
              <span className="w-5 h-5 border-2 border-primary/30 border-t-primary rounded-full animate-spin" />
              Drafting your head start…
            </div>
          ) : (
            <Markdown>{draft}</Markdown>
          )}
        </div>

        <div className="flex items-center justify-between mt-unit-md gap-2">
          <span className="text-label-md text-on-surface-variant flex items-center gap-1">
            <span className="material-symbols-outlined text-[14px] text-primary">
              {usedAi ? "auto_awesome" : "description"}
            </span>
            {usedAi ? "Generated by Gemini" : "Smart template"}
          </span>
          <div className="flex gap-2">
            <button
              onClick={() => load(kind, true)}
              disabled={loading}
              className="px-4 py-2 rounded-xl text-on-surface-variant hover:bg-surface-container-high flex items-center gap-1 disabled:opacity-50"
            >
              <span className="material-symbols-outlined text-base">refresh</span> Regenerate
            </button>
            <button
              onClick={copy}
              disabled={loading}
              className="px-5 py-2 bg-primary text-on-primary-fixed rounded-xl font-bold flex items-center gap-2 disabled:opacity-50"
            >
              <span className="material-symbols-outlined text-base">
                {copied ? "check" : "content_copy"}
              </span>
              {copied ? "Copied!" : "Copy"}
            </button>
          </div>
        </div>
      </motion.div>
    </motion.div>
  );
}
